//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Program.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paint_Program.Languages.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinselhärte.
        /// </summary>
        internal static string brushsettings_brush_hardness {
            get {
                return ResourceManager.GetString("brushsettings_brush_hardness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinselgröße.
        /// </summary>
        internal static string brushsettings_brush_size {
            get {
                return ResourceManager.GetString("brushsettings_brush_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptfarbe.
        /// </summary>
        internal static string brushsettings_color_primary {
            get {
                return ResourceManager.GetString("brushsettings_color_primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zweite Farbe.
        /// </summary>
        internal static string brushsettings_color_secondary {
            get {
                return ResourceManager.GetString("brushsettings_color_secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string edit_menu {
            get {
                return ResourceManager.GetString("edit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellen.
        /// </summary>
        internal static string edit_menu_redo {
            get {
                return ResourceManager.GetString("edit_menu_redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildgröße.
        /// </summary>
        internal static string edit_menu_resize {
            get {
                return ResourceManager.GetString("edit_menu_resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig machen.
        /// </summary>
        internal static string edit_menu_undo {
            get {
                return ResourceManager.GetString("edit_menu_undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern von Projekt.
        /// </summary>
        internal static string error_save_project {
            get {
                return ResourceManager.GetString("error_save_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie eine Bilddatei.
        /// </summary>
        internal static string exportdialog_title {
            get {
                return ResourceManager.GetString("exportdialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string file_menu {
            get {
                return ResourceManager.GetString("file_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild exportieren.
        /// </summary>
        internal static string file_menu_export {
            get {
                return ResourceManager.GetString("file_menu_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Google Drive exportieren.
        /// </summary>
        internal static string file_menu_googledrive {
            get {
                return ResourceManager.GetString("file_menu_googledrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild importieren.
        /// </summary>
        internal static string file_menu_import {
            get {
                return ResourceManager.GetString("file_menu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        internal static string file_menu_new {
            get {
                return ResourceManager.GetString("file_menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        internal static string file_menu_open {
            get {
                return ResourceManager.GetString("file_menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sparen.
        /// </summary>
        internal static string file_menu_save {
            get {
                return ResourceManager.GetString("file_menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Speichern ist ein Fehler aufgetreten..
        /// </summary>
        internal static string filesave_error {
            get {
                return ResourceManager.GetString("filesave_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Bild|*.bmp|GIF Bild|*.gif|Icon Bild|*.ico|JPeg Bild|*.jpg|PNG Bild|*.png|TIFF Bild|*.tiff&quot;.
        /// </summary>
        internal static string filesave_filter {
            get {
                return ResourceManager.GetString("filesave_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei wurde gespeichert!.
        /// </summary>
        internal static string filesave_saved {
            get {
                return ResourceManager.GetString("filesave_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie eine Bilddatei.
        /// </summary>
        internal static string filesave_title {
            get {
                return ResourceManager.GetString("filesave_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Erstellen der Google Drive-Datei:.
        /// </summary>
        internal static string gdrivesavedialog_error {
            get {
                return ResourceManager.GetString("gdrivesavedialog_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateiname.
        /// </summary>
        internal static string gdrivesavedialog_filename {
            get {
                return ResourceManager.GetString("gdrivesavedialog_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateityp.
        /// </summary>
        internal static string gdrivesavedialog_filetype {
            get {
                return ResourceManager.GetString("gdrivesavedialog_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Google Drive speichern.
        /// </summary>
        internal static string gdrivesavedialog_title {
            get {
                return ResourceManager.GetString("gdrivesavedialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien|*.*|Bitmap Bild|*.bmp|GIF Bild|*.gif|Icon Bild|*.ico|JPeg Bild|*.jpg|PNG Bild|*.png|TIFF Bild|*.tiff&quot;.
        /// </summary>
        internal static string imageimport_dialog_filter {
            get {
                return ResourceManager.GetString("imageimport_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen Sie eine Bilddatei.
        /// </summary>
        internal static string imageimport_dialog_title {
            get {
                return ResourceManager.GetString("imageimport_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Öffnen ist ein Fehler aufgetreten..
        /// </summary>
        internal static string imageimport_error {
            get {
                return ResourceManager.GetString("imageimport_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtbar.
        /// </summary>
        internal static string layeritem_checkbox_visible {
            get {
                return ResourceManager.GetString("layeritem_checkbox_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen Sie eine Projektdatei.
        /// </summary>
        internal static string loadproject_dialog_title {
            get {
                return ResourceManager.GetString("loadproject_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe.
        /// </summary>
        internal static string newproject_dialog_height {
            get {
                return ResourceManager.GetString("newproject_dialog_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to einreichen.
        /// </summary>
        internal static string newproject_dialog_submit {
            get {
                return ResourceManager.GetString("newproject_dialog_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Projekt.
        /// </summary>
        internal static string newproject_dialog_title {
            get {
                return ResourceManager.GetString("newproject_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        internal static string newproject_dialog_width {
            get {
                return ResourceManager.GetString("newproject_dialog_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präferenzen.
        /// </summary>
        internal static string preferences_menu {
            get {
                return ResourceManager.GetString("preferences_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        internal static string preferences_menu_international {
            get {
                return ResourceManager.GetString("preferences_menu_international", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasserzeichen.
        /// </summary>
        internal static string preferences_menu_watermark {
            get {
                return ResourceManager.GetString("preferences_menu_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild einstellen.
        /// </summary>
        internal static string preferences_menu_watermark_set {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasserzeichen anzeigen.
        /// </summary>
        internal static string preferences_menu_watermark_show {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stil.
        /// </summary>
        internal static string preferences_menu_watermark_style {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Boden.
        /// </summary>
        internal static string preferences_menu_watermark_style_singlebottom {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_singlebottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single zentriert.
        /// </summary>
        internal static string preferences_menu_watermark_style_singlecentered {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_singlecentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefliest.
        /// </summary>
        internal static string preferences_menu_watermark_style_tiled {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_tiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Paint Projekt|*.lep|Alle Dateien|*.*.
        /// </summary>
        internal static string projectopen_dialog_filter {
            get {
                return ResourceManager.GetString("projectopen_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen Sie ein Projekt.
        /// </summary>
        internal static string projectopen_dialog_title {
            get {
                return ResourceManager.GetString("projectopen_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Öffnen des Projekts ist ein Fehler aufgetreten..
        /// </summary>
        internal static string projectopen_error {
            get {
                return ResourceManager.GetString("projectopen_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Datein|*.*|Le Paint Projekt|*.lep|Gif|*.gif.
        /// </summary>
        internal static string projectsave_dialog_filter {
            get {
                return ResourceManager.GetString("projectsave_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt speichern.
        /// </summary>
        internal static string projectsave_dialog_title {
            get {
                return ResourceManager.GetString("projectsave_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Speichern wird ein Fehler aufgetreten..
        /// </summary>
        internal static string projectsave_error {
            get {
                return ResourceManager.GetString("projectsave_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt gespeichert!.
        /// </summary>
        internal static string projectsave_saved {
            get {
                return ResourceManager.GetString("projectsave_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche.
        /// </summary>
        internal static string resource_languagename {
            get {
                return ResourceManager.GetString("resource_languagename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Paint Underground.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild importieren.
        /// </summary>
        internal static string toolstripmenu_import {
            get {
                return ResourceManager.GetString("toolstripmenu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Projekt.
        /// </summary>
        internal static string toolstripmenu_new {
            get {
                return ResourceManager.GetString("toolstripmenu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt speichern.
        /// </summary>
        internal static string toolstripmenu_save {
            get {
                return ResourceManager.GetString("toolstripmenu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinselwerkzeug.
        /// </summary>
        internal static string tooltip_brush {
            get {
                return ResourceManager.GetString("tooltip_brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbeimer Werkzeug.
        /// </summary>
        internal static string tooltip_bucket {
            get {
                return ResourceManager.GetString("tooltip_bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbauswahlwerkzeug.
        /// </summary>
        internal static string tooltip_colorselect {
            get {
                return ResourceManager.GetString("tooltip_colorselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiergummi.
        /// </summary>
        internal static string tooltip_eraser {
            get {
                return ResourceManager.GetString("tooltip_eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grüner Bildschirm.
        /// </summary>
        internal static string tooltip_greenscreen {
            get {
                return ResourceManager.GetString("tooltip_greenscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linienwerkzeug.
        /// </summary>
        internal static string tooltip_line {
            get {
                return ResourceManager.GetString("tooltip_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkzeug Verschieben.
        /// </summary>
        internal static string tooltip_move {
            get {
                return ResourceManager.GetString("tooltip_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleistift-Werkzeug.
        /// </summary>
        internal static string tooltip_pencil {
            get {
                return ResourceManager.GetString("tooltip_pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahlwerkzeug.
        /// </summary>
        internal static string tooltip_selection {
            get {
                return ResourceManager.GetString("tooltip_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Werkzeug.
        /// </summary>
        internal static string tooltip_text {
            get {
                return ResourceManager.GetString("tooltip_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aussicht.
        /// </summary>
        internal static string view_menu {
            get {
                return ResourceManager.GetString("view_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitterlinien umschalten.
        /// </summary>
        internal static string view_menu_grid {
            get {
                return ResourceManager.GetString("view_menu_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch.
        /// </summary>
        internal static string view_menu_grid_auto {
            get {
                return ResourceManager.GetString("view_menu_grid_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet-Modus.
        /// </summary>
        internal static string view_menu_tablet {
            get {
                return ResourceManager.GetString("view_menu_tablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkzeuge anzeigen.
        /// </summary>
        internal static string view_menu_tools {
            get {
                return ResourceManager.GetString("view_menu_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien|*.*.
        /// </summary>
        internal static string watermarkdialog_filter {
            get {
                return ResourceManager.GetString("watermarkdialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle ein Wasserzeichen.
        /// </summary>
        internal static string watermarkdialog_title {
            get {
                return ResourceManager.GetString("watermarkdialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
    }
}
