//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Program.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paint_Program.Languages.es-ES", typeof(es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dureza del pincel.
        /// </summary>
        internal static string brushsettings_brush_hardness {
            get {
                return ResourceManager.GetString("brushsettings_brush_hardness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del pincel.
        /// </summary>
        internal static string brushsettings_brush_size {
            get {
                return ResourceManager.GetString("brushsettings_brush_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color principal.
        /// </summary>
        internal static string brushsettings_color_primary {
            get {
                return ResourceManager.GetString("brushsettings_color_primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo color.
        /// </summary>
        internal static string brushsettings_color_secondary {
            get {
                return ResourceManager.GetString("brushsettings_color_secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string edit_menu {
            get {
                return ResourceManager.GetString("edit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehacer.
        /// </summary>
        internal static string edit_menu_redo {
            get {
                return ResourceManager.GetString("edit_menu_redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionar.
        /// </summary>
        internal static string edit_menu_resize {
            get {
                return ResourceManager.GetString("edit_menu_resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshacer.
        /// </summary>
        internal static string edit_menu_undo {
            get {
                return ResourceManager.GetString("edit_menu_undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Guardar el Proyecto.
        /// </summary>
        internal static string error_save_project {
            get {
                return ResourceManager.GetString("error_save_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar un Archivo de Imagen.
        /// </summary>
        internal static string exportdialog_title {
            get {
                return ResourceManager.GetString("exportdialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string file_menu {
            get {
                return ResourceManager.GetString("file_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar la Imagen.
        /// </summary>
        internal static string file_menu_export {
            get {
                return ResourceManager.GetString("file_menu_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Imagen.
        /// </summary>
        internal static string file_menu_import {
            get {
                return ResourceManager.GetString("file_menu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string file_menu_new {
            get {
                return ResourceManager.GetString("file_menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abierto.
        /// </summary>
        internal static string file_menu_open {
            get {
                return ResourceManager.GetString("file_menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string file_menu_save {
            get {
                return ResourceManager.GetString("file_menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los archivos|*.*|Bitmap Imagen|*.bmp|GIF Imagen|*.gif|Icon Imagen|*.ico|JPeg Imagen|*.jpg|PNG Imagen|*.png|TIFF Imagen|*.tiff&quot;.
        /// </summary>
        internal static string imageimport_dialog_filter {
            get {
                return ResourceManager.GetString("imageimport_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir un Archivo de Imagen.
        /// </summary>
        internal static string imageimport_dialog_title {
            get {
                return ResourceManager.GetString("imageimport_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al abrir..
        /// </summary>
        internal static string imageimport_error {
            get {
                return ResourceManager.GetString("imageimport_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string layeritem_checkbox_visible {
            get {
                return ResourceManager.GetString("layeritem_checkbox_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir un Archivo de Proyecto.
        /// </summary>
        internal static string loadproject_dialog_title {
            get {
                return ResourceManager.GetString("loadproject_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        internal static string newproject_dialog_height {
            get {
                return ResourceManager.GetString("newproject_dialog_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string newproject_dialog_submit {
            get {
                return ResourceManager.GetString("newproject_dialog_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Proyecto.
        /// </summary>
        internal static string newproject_dialog_title {
            get {
                return ResourceManager.GetString("newproject_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchura.
        /// </summary>
        internal static string newproject_dialog_width {
            get {
                return ResourceManager.GetString("newproject_dialog_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferencias.
        /// </summary>
        internal static string preferences_menu {
            get {
                return ResourceManager.GetString("preferences_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internacional.
        /// </summary>
        internal static string preferences_menu_international {
            get {
                return ResourceManager.GetString("preferences_menu_international", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filigrana.
        /// </summary>
        internal static string preferences_menu_watermark {
            get {
                return ResourceManager.GetString("preferences_menu_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer Imagen.
        /// </summary>
        internal static string preferences_menu_watermark_set {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Filigrana.
        /// </summary>
        internal static string preferences_menu_watermark_show {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilo.
        /// </summary>
        internal static string preferences_menu_watermark_style {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abajo a la derecha.
        /// </summary>
        internal static string preferences_menu_watermark_style_singlebottom {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_singlebottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Centrado.
        /// </summary>
        internal static string preferences_menu_watermark_style_singlecentered {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_singlecentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrón de Mosaico.
        /// </summary>
        internal static string preferences_menu_watermark_style_tiled {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_tiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Paint Project|*.lep|Todos los archivos|*.*.
        /// </summary>
        internal static string projectopen_dialog_filter {
            get {
                return ResourceManager.GetString("projectopen_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir un archivo de proyecto.
        /// </summary>
        internal static string projectopen_dialog_title {
            get {
                return ResourceManager.GetString("projectopen_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al abrir..
        /// </summary>
        internal static string projectopen_error {
            get {
                return ResourceManager.GetString("projectopen_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Paint Project File|*.lep|Todos los archivos|*.*.
        /// </summary>
        internal static string projectsave_dialog_filter {
            get {
                return ResourceManager.GetString("projectsave_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Proyecto.
        /// </summary>
        internal static string projectsave_dialog_title {
            get {
                return ResourceManager.GetString("projectsave_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al guardar..
        /// </summary>
        internal static string projectsave_error {
            get {
                return ResourceManager.GetString("projectsave_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto guardado!.
        /// </summary>
        internal static string projectsave_saved {
            get {
                return ResourceManager.GetString("projectsave_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string resource_languagename {
            get {
                return ResourceManager.GetString("resource_languagename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Paint Underground.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Imagen.
        /// </summary>
        internal static string toolstripmenu_import {
            get {
                return ResourceManager.GetString("toolstripmenu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Proyecto.
        /// </summary>
        internal static string toolstripmenu_new {
            get {
                return ResourceManager.GetString("toolstripmenu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Proyecto.
        /// </summary>
        internal static string toolstripmenu_save {
            get {
                return ResourceManager.GetString("toolstripmenu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincel.
        /// </summary>
        internal static string tooltip_brush {
            get {
                return ResourceManager.GetString("tooltip_brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta Bote de Pintura.
        /// </summary>
        internal static string tooltip_bucket {
            get {
                return ResourceManager.GetString("tooltip_bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta de Selección de Color.
        /// </summary>
        internal static string tooltip_colorselect {
            get {
                return ResourceManager.GetString("tooltip_colorselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrador.
        /// </summary>
        internal static string tooltip_eraser {
            get {
                return ResourceManager.GetString("tooltip_eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta de pantalla verde.
        /// </summary>
        internal static string tooltip_greenscreen {
            get {
                return ResourceManager.GetString("tooltip_greenscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta de línea.
        /// </summary>
        internal static string tooltip_line {
            get {
                return ResourceManager.GetString("tooltip_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta Lápiz.
        /// </summary>
        internal static string tooltip_pencil {
            get {
                return ResourceManager.GetString("tooltip_pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta de selección.
        /// </summary>
        internal static string tooltip_selection {
            get {
                return ResourceManager.GetString("tooltip_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta de Texto.
        /// </summary>
        internal static string tooltip_text {
            get {
                return ResourceManager.GetString("tooltip_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        internal static string view_menu {
            get {
                return ResourceManager.GetString("view_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternar líneas de cuadrícula.
        /// </summary>
        internal static string view_menu_grid {
            get {
                return ResourceManager.GetString("view_menu_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automático.
        /// </summary>
        internal static string view_menu_grid_auto {
            get {
                return ResourceManager.GetString("view_menu_grid_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Tablet.
        /// </summary>
        internal static string view_menu_tablet {
            get {
                return ResourceManager.GetString("view_menu_tablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Herramientas.
        /// </summary>
        internal static string view_menu_tools {
            get {
                return ResourceManager.GetString("view_menu_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los archivos|*.*.
        /// </summary>
        internal static string watermarkdialog_filter {
            get {
                return ResourceManager.GetString("watermarkdialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una filigrana.
        /// </summary>
        internal static string watermarkdialog_title {
            get {
                return ResourceManager.GetString("watermarkdialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfocar.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
    }
}
