//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint_Program.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paint_Program.Languages.fr-FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dureté de la brosse.
        /// </summary>
        internal static string brushsettings_brush_hardness {
            get {
                return ResourceManager.GetString("brushsettings_brush_hardness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille de la brosse.
        /// </summary>
        internal static string brushsettings_brush_size {
            get {
                return ResourceManager.GetString("brushsettings_brush_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur principale.
        /// </summary>
        internal static string brushsettings_color_primary {
            get {
                return ResourceManager.GetString("brushsettings_color_primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuxième couleur.
        /// </summary>
        internal static string brushsettings_color_secondary {
            get {
                return ResourceManager.GetString("brushsettings_color_secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string edit_menu {
            get {
                return ResourceManager.GetString("edit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refaire.
        /// </summary>
        internal static string edit_menu_redo {
            get {
                return ResourceManager.GetString("edit_menu_redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille de l&apos;image.
        /// </summary>
        internal static string edit_menu_resize {
            get {
                return ResourceManager.GetString("edit_menu_resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string edit_menu_undo {
            get {
                return ResourceManager.GetString("edit_menu_undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;enregistrement du projet.
        /// </summary>
        internal static string error_save_project {
            get {
                return ResourceManager.GetString("error_save_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer un fichier d&apos;image.
        /// </summary>
        internal static string exportdialog_title {
            get {
                return ResourceManager.GetString("exportdialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier.
        /// </summary>
        internal static string file_menu {
            get {
                return ResourceManager.GetString("file_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter l&apos;image.
        /// </summary>
        internal static string file_menu_export {
            get {
                return ResourceManager.GetString("file_menu_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer une image.
        /// </summary>
        internal static string file_menu_import {
            get {
                return ResourceManager.GetString("file_menu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        internal static string file_menu_new {
            get {
                return ResourceManager.GetString("file_menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string file_menu_open {
            get {
                return ResourceManager.GetString("file_menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string file_menu_save {
            get {
                return ResourceManager.GetString("file_menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les fichiers|*.*|Bitmap Image|*.bmp|GIF Image|*.gif|Icon Image|*.ico|JPeg Image|*.jpg|PNG Image|*.png|TIFF Image|*.tiff&quot;.
        /// </summary>
        internal static string imageimport_dialog_filter {
            get {
                return ResourceManager.GetString("imageimport_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un fichier image.
        /// </summary>
        internal static string imageimport_dialog_title {
            get {
                return ResourceManager.GetString("imageimport_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de l&apos;ouverture..
        /// </summary>
        internal static string imageimport_error {
            get {
                return ResourceManager.GetString("imageimport_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string layeritem_checkbox_visible {
            get {
                return ResourceManager.GetString("layeritem_checkbox_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un fichier de projet.
        /// </summary>
        internal static string loadproject_dialog_title {
            get {
                return ResourceManager.GetString("loadproject_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Taille.
        /// </summary>
        internal static string newproject_dialog_height {
            get {
                return ResourceManager.GetString("newproject_dialog_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumettre.
        /// </summary>
        internal static string newproject_dialog_submit {
            get {
                return ResourceManager.GetString("newproject_dialog_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau Projet.
        /// </summary>
        internal static string newproject_dialog_title {
            get {
                return ResourceManager.GetString("newproject_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur.
        /// </summary>
        internal static string newproject_dialog_width {
            get {
                return ResourceManager.GetString("newproject_dialog_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préférences.
        /// </summary>
        internal static string preferences_menu {
            get {
                return ResourceManager.GetString("preferences_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        internal static string preferences_menu_international {
            get {
                return ResourceManager.GetString("preferences_menu_international", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filigrane.
        /// </summary>
        internal static string preferences_menu_watermark {
            get {
                return ResourceManager.GetString("preferences_menu_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir l&apos;image.
        /// </summary>
        internal static string preferences_menu_watermark_set {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le filigrane.
        /// </summary>
        internal static string preferences_menu_watermark_show {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string preferences_menu_watermark_style {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bas Simple.
        /// </summary>
        internal static string preferences_menu_watermark_style_singlebottom {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_singlebottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centré.
        /// </summary>
        internal static string preferences_menu_watermark_style_singlecentered {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_singlecentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrelage.
        /// </summary>
        internal static string preferences_menu_watermark_style_tiled {
            get {
                return ResourceManager.GetString("preferences_menu_watermark_style_tiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet Le Paint|*.lep|Tous les fichiers|*.*.
        /// </summary>
        internal static string projectopen_dialog_filter {
            get {
                return ResourceManager.GetString("projectopen_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un fichier de projet.
        /// </summary>
        internal static string projectopen_dialog_title {
            get {
                return ResourceManager.GetString("projectopen_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de l&apos;ouverture du projet..
        /// </summary>
        internal static string projectopen_error {
            get {
                return ResourceManager.GetString("projectopen_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet Le Paint|*.lep|Tous les fichiers|*.*.
        /// </summary>
        internal static string projectsave_dialog_filter {
            get {
                return ResourceManager.GetString("projectsave_dialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder le Projet.
        /// </summary>
        internal static string projectsave_dialog_title {
            get {
                return ResourceManager.GetString("projectsave_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de l&apos;enregistrement..
        /// </summary>
        internal static string projectsave_error {
            get {
                return ResourceManager.GetString("projectsave_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet Enregistré!.
        /// </summary>
        internal static string projectsave_saved {
            get {
                return ResourceManager.GetString("projectsave_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string resource_languagename {
            get {
                return ResourceManager.GetString("resource_languagename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Paint Underground.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer une image.
        /// </summary>
        internal static string toolstripmenu_import {
            get {
                return ResourceManager.GetString("toolstripmenu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau projet.
        /// </summary>
        internal static string toolstripmenu_new {
            get {
                return ResourceManager.GetString("toolstripmenu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder le projet.
        /// </summary>
        internal static string toolstripmenu_save {
            get {
                return ResourceManager.GetString("toolstripmenu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil Pinceau.
        /// </summary>
        internal static string tooltip_brush {
            get {
                return ResourceManager.GetString("tooltip_brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil de seau de peinture.
        /// </summary>
        internal static string tooltip_bucket {
            get {
                return ResourceManager.GetString("tooltip_bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil de sélection des couleurs.
        /// </summary>
        internal static string tooltip_colorselect {
            get {
                return ResourceManager.GetString("tooltip_colorselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Gomme.
        /// </summary>
        internal static string tooltip_eraser {
            get {
                return ResourceManager.GetString("tooltip_eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil écran vert.
        /// </summary>
        internal static string tooltip_greenscreen {
            get {
                return ResourceManager.GetString("tooltip_greenscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil de Ligne.
        /// </summary>
        internal static string tooltip_line {
            get {
                return ResourceManager.GetString("tooltip_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil Crayon.
        /// </summary>
        internal static string tooltip_pencil {
            get {
                return ResourceManager.GetString("tooltip_pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil de sélection.
        /// </summary>
        internal static string tooltip_selection {
            get {
                return ResourceManager.GetString("tooltip_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outil de texte.
        /// </summary>
        internal static string tooltip_text {
            get {
                return ResourceManager.GetString("tooltip_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue.
        /// </summary>
        internal static string view_menu {
            get {
                return ResourceManager.GetString("view_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basculer les Lignes de Grille.
        /// </summary>
        internal static string view_menu_grid {
            get {
                return ResourceManager.GetString("view_menu_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatique.
        /// </summary>
        internal static string view_menu_grid_auto {
            get {
                return ResourceManager.GetString("view_menu_grid_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Tablette.
        /// </summary>
        internal static string view_menu_tablet {
            get {
                return ResourceManager.GetString("view_menu_tablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les outils.
        /// </summary>
        internal static string view_menu_tools {
            get {
                return ResourceManager.GetString("view_menu_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les fichiers|*.*.
        /// </summary>
        internal static string watermarkdialog_filter {
            get {
                return ResourceManager.GetString("watermarkdialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un Filigrane.
        /// </summary>
        internal static string watermarkdialog_title {
            get {
                return ResourceManager.GetString("watermarkdialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
    }
}
